export const enum ProfileActions {
  SET_VALUES = 'SET_VALUES',
  SET_EMAIL_VISIBLE = 'SET_EMAIL_VISIBLE',
  SET_NAME_VISIBLE = 'SET_NAME_VISIBLE',
  SET_FORM_VALID = 'SET_FORM_VALID',
  SET_ERROR = 'SET_ERROR',
  RESET = 'RESET',
}
